services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540" 
    networks:
      - redis-network
    restart: always
    volumes:
      - redisinsight-data:/var/lib/redisinsight-data/data

networks:
  redis-network:
    driver: bridge

volumes:
  redisinsight-data: