# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zonkgameservice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'zonkgameservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15zonkgameservice.proto\x12\x04zonk\"6\n\x14SelectedDicesRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\r\n\x05\x64ices\x18\x02 \x03(\x05\"&\n\x15SelectedDicesResponse\x12\r\n\x05\x64ices\x18\x01 \x03(\x05\".\n\x1b\x43ontinuationDecisionRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"5\n\x1c\x43ontinuationDecisionResponse\x12\x15\n\rcontinue_game\x18\x01 \x01(\x08\x32\xbc\x01\n\x0bZonkService\x12K\n\x10GetSelectedDices\x12\x1a.zonk.SelectedDicesRequest\x1a\x1b.zonk.SelectedDicesResponse\x12`\n\x17GetContinuationDecision\x12!.zonk.ContinuationDecisionRequest\x1a\".zonk.ContinuationDecisionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zonkgameservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SELECTEDDICESREQUEST']._serialized_start=31
  _globals['_SELECTEDDICESREQUEST']._serialized_end=85
  _globals['_SELECTEDDICESRESPONSE']._serialized_start=87
  _globals['_SELECTEDDICESRESPONSE']._serialized_end=125
  _globals['_CONTINUATIONDECISIONREQUEST']._serialized_start=127
  _globals['_CONTINUATIONDECISIONREQUEST']._serialized_end=173
  _globals['_CONTINUATIONDECISIONRESPONSE']._serialized_start=175
  _globals['_CONTINUATIONDECISIONRESPONSE']._serialized_end=228
  _globals['_ZONKSERVICE']._serialized_start=231
  _globals['_ZONKSERVICE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
